spring.application.name=shopsflow

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.aqfomuvlvharufhbyywe
spring.datasource.password=Kakarrot56@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=Rz+rmzEk9kflpPS5b+LgUlOYSCpKldOBhtwFilbakT4=             
jwt.expiration=86400000  